// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef PROTOBUF_protocol_2eproto__INCLUDED
#define PROTOBUF_protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protocol_2eproto();
void protobuf_InitDefaults_protocol_2eproto();
void protobuf_AssignDesc_protocol_2eproto();
void protobuf_ShutdownFile_protocol_2eproto();

class LoginRequest;
class LoginResponse;
class SyncInfo_C;
class SyncInfo_S;
class SyncInfo_S_User;
class UserInfo;

// ===================================================================

class LoginRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LoginRequest) */ {
 public:
  LoginRequest();
  virtual ~LoginRequest();

  LoginRequest(const LoginRequest& from);

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRequest& default_instance();

  static const LoginRequest* internal_default_instance();

  void Swap(LoginRequest* other);

  // implements Message ----------------------------------------------

  inline LoginRequest* New() const { return New(NULL); }

  LoginRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRequest& from);
  void MergeFrom(const LoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginRequest* other);
  void UnsafeMergeFrom(const LoginRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string passwd = 2;
  void clear_passwd();
  static const int kPasswdFieldNumber = 2;
  const ::std::string& passwd() const;
  void set_passwd(const ::std::string& value);
  void set_passwd(const char* value);
  void set_passwd(const char* value, size_t size);
  ::std::string* mutable_passwd();
  ::std::string* release_passwd();
  void set_allocated_passwd(::std::string* passwd);

  // @@protoc_insertion_point(class_scope:LoginRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr passwd_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<LoginRequest> LoginRequest_default_instance_;

// -------------------------------------------------------------------

class LoginResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LoginResponse) */ {
 public:
  LoginResponse();
  virtual ~LoginResponse();

  LoginResponse(const LoginResponse& from);

  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginResponse& default_instance();

  static const LoginResponse* internal_default_instance();

  void Swap(LoginResponse* other);

  // implements Message ----------------------------------------------

  inline LoginResponse* New() const { return New(NULL); }

  LoginResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginResponse& from);
  void MergeFrom(const LoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginResponse* other);
  void UnsafeMergeFrom(const LoginResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 response_code = 1;
  void clear_response_code();
  static const int kResponseCodeFieldNumber = 1;
  ::google::protobuf::int32 response_code() const;
  void set_response_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LoginResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 response_code_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<LoginResponse> LoginResponse_default_instance_;

// -------------------------------------------------------------------

class UserInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UserInfo) */ {
 public:
  UserInfo();
  virtual ~UserInfo();

  UserInfo(const UserInfo& from);

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfo& default_instance();

  static const UserInfo* internal_default_instance();

  void Swap(UserInfo* other);

  // implements Message ----------------------------------------------

  inline UserInfo* New() const { return New(NULL); }

  UserInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserInfo& from);
  void MergeFrom(const UserInfo& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UserInfo* other);
  void UnsafeMergeFrom(const UserInfo& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 identify_id = 1;
  void clear_identify_id();
  static const int kIdentifyIdFieldNumber = 1;
  ::google::protobuf::int32 identify_id() const;
  void set_identify_id(::google::protobuf::int32 value);

  // optional int32 channel_num = 2;
  void clear_channel_num();
  static const int kChannelNumFieldNumber = 2;
  ::google::protobuf::int32 channel_num() const;
  void set_channel_num(::google::protobuf::int32 value);

  // optional int32 session_num = 3;
  void clear_session_num();
  static const int kSessionNumFieldNumber = 3;
  ::google::protobuf::int32 session_num() const;
  void set_session_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UserInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 identify_id_;
  ::google::protobuf::int32 channel_num_;
  ::google::protobuf::int32 session_num_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<UserInfo> UserInfo_default_instance_;

// -------------------------------------------------------------------

class SyncInfo_S_User : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SyncInfo_S.User) */ {
 public:
  SyncInfo_S_User();
  virtual ~SyncInfo_S_User();

  SyncInfo_S_User(const SyncInfo_S_User& from);

  inline SyncInfo_S_User& operator=(const SyncInfo_S_User& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncInfo_S_User& default_instance();

  static const SyncInfo_S_User* internal_default_instance();

  void Swap(SyncInfo_S_User* other);

  // implements Message ----------------------------------------------

  inline SyncInfo_S_User* New() const { return New(NULL); }

  SyncInfo_S_User* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SyncInfo_S_User& from);
  void MergeFrom(const SyncInfo_S_User& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SyncInfo_S_User* other);
  void UnsafeMergeFrom(const SyncInfo_S_User& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int32 user_id() const;
  void set_user_id(::google::protobuf::int32 value);

  // optional int32 x_pos = 2;
  void clear_x_pos();
  static const int kXPosFieldNumber = 2;
  ::google::protobuf::int32 x_pos() const;
  void set_x_pos(::google::protobuf::int32 value);

  // optional int32 y_pos = 3;
  void clear_y_pos();
  static const int kYPosFieldNumber = 3;
  ::google::protobuf::int32 y_pos() const;
  void set_y_pos(::google::protobuf::int32 value);

  // optional int32 vec = 4;
  void clear_vec();
  static const int kVecFieldNumber = 4;
  ::google::protobuf::int32 vec() const;
  void set_vec(::google::protobuf::int32 value);

  // optional int32 type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional int32 A_type_pow = 6;
  void clear_a_type_pow();
  static const int kATypePowFieldNumber = 6;
  ::google::protobuf::int32 a_type_pow() const;
  void set_a_type_pow(::google::protobuf::int32 value);

  // optional int32 B_type_pow = 7;
  void clear_b_type_pow();
  static const int kBTypePowFieldNumber = 7;
  ::google::protobuf::int32 b_type_pow() const;
  void set_b_type_pow(::google::protobuf::int32 value);

  // optional int32 C_type_pow = 8;
  void clear_c_type_pow();
  static const int kCTypePowFieldNumber = 8;
  ::google::protobuf::int32 c_type_pow() const;
  void set_c_type_pow(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SyncInfo_S.User)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 user_id_;
  ::google::protobuf::int32 x_pos_;
  ::google::protobuf::int32 y_pos_;
  ::google::protobuf::int32 vec_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 a_type_pow_;
  ::google::protobuf::int32 b_type_pow_;
  ::google::protobuf::int32 c_type_pow_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SyncInfo_S_User> SyncInfo_S_User_default_instance_;

// -------------------------------------------------------------------

class SyncInfo_S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SyncInfo_S) */ {
 public:
  SyncInfo_S();
  virtual ~SyncInfo_S();

  SyncInfo_S(const SyncInfo_S& from);

  inline SyncInfo_S& operator=(const SyncInfo_S& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncInfo_S& default_instance();

  static const SyncInfo_S* internal_default_instance();

  void Swap(SyncInfo_S* other);

  // implements Message ----------------------------------------------

  inline SyncInfo_S* New() const { return New(NULL); }

  SyncInfo_S* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SyncInfo_S& from);
  void MergeFrom(const SyncInfo_S& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SyncInfo_S* other);
  void UnsafeMergeFrom(const SyncInfo_S& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SyncInfo_S_User User;

  // accessors -------------------------------------------------------

  // repeated .SyncInfo_S.User users = 1;
  int users_size() const;
  void clear_users();
  static const int kUsersFieldNumber = 1;
  const ::SyncInfo_S_User& users(int index) const;
  ::SyncInfo_S_User* mutable_users(int index);
  ::SyncInfo_S_User* add_users();
  ::google::protobuf::RepeatedPtrField< ::SyncInfo_S_User >*
      mutable_users();
  const ::google::protobuf::RepeatedPtrField< ::SyncInfo_S_User >&
      users() const;

  // @@protoc_insertion_point(class_scope:SyncInfo_S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::SyncInfo_S_User > users_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SyncInfo_S> SyncInfo_S_default_instance_;

// -------------------------------------------------------------------

class SyncInfo_C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SyncInfo_C) */ {
 public:
  SyncInfo_C();
  virtual ~SyncInfo_C();

  SyncInfo_C(const SyncInfo_C& from);

  inline SyncInfo_C& operator=(const SyncInfo_C& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncInfo_C& default_instance();

  static const SyncInfo_C* internal_default_instance();

  void Swap(SyncInfo_C* other);

  // implements Message ----------------------------------------------

  inline SyncInfo_C* New() const { return New(NULL); }

  SyncInfo_C* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SyncInfo_C& from);
  void MergeFrom(const SyncInfo_C& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SyncInfo_C* other);
  void UnsafeMergeFrom(const SyncInfo_C& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int32 user_id() const;
  void set_user_id(::google::protobuf::int32 value);

  // optional int32 x_pos = 2;
  void clear_x_pos();
  static const int kXPosFieldNumber = 2;
  ::google::protobuf::int32 x_pos() const;
  void set_x_pos(::google::protobuf::int32 value);

  // optional int32 y_pos = 3;
  void clear_y_pos();
  static const int kYPosFieldNumber = 3;
  ::google::protobuf::int32 y_pos() const;
  void set_y_pos(::google::protobuf::int32 value);

  // optional int32 vec = 4;
  void clear_vec();
  static const int kVecFieldNumber = 4;
  ::google::protobuf::int32 vec() const;
  void set_vec(::google::protobuf::int32 value);

  // optional int32 type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional int32 A_type_pow = 6;
  void clear_a_type_pow();
  static const int kATypePowFieldNumber = 6;
  ::google::protobuf::int32 a_type_pow() const;
  void set_a_type_pow(::google::protobuf::int32 value);

  // optional int32 B_type_pow = 7;
  void clear_b_type_pow();
  static const int kBTypePowFieldNumber = 7;
  ::google::protobuf::int32 b_type_pow() const;
  void set_b_type_pow(::google::protobuf::int32 value);

  // optional int32 C_type_pow = 8;
  void clear_c_type_pow();
  static const int kCTypePowFieldNumber = 8;
  ::google::protobuf::int32 c_type_pow() const;
  void set_c_type_pow(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SyncInfo_C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 user_id_;
  ::google::protobuf::int32 x_pos_;
  ::google::protobuf::int32 y_pos_;
  ::google::protobuf::int32 vec_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 a_type_pow_;
  ::google::protobuf::int32 b_type_pow_;
  ::google::protobuf::int32 c_type_pow_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SyncInfo_C> SyncInfo_C_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRequest

// optional string id = 1;
inline void LoginRequest::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginRequest::id() const {
  // @@protoc_insertion_point(field_get:LoginRequest.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LoginRequest.id)
}
inline void LoginRequest::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LoginRequest.id)
}
inline void LoginRequest::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LoginRequest.id)
}
inline ::std::string* LoginRequest::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:LoginRequest.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_id() {
  // @@protoc_insertion_point(field_release:LoginRequest.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:LoginRequest.id)
}

// optional string passwd = 2;
inline void LoginRequest::clear_passwd() {
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginRequest::passwd() const {
  // @@protoc_insertion_point(field_get:LoginRequest.passwd)
  return passwd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_passwd(const ::std::string& value) {
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LoginRequest.passwd)
}
inline void LoginRequest::set_passwd(const char* value) {
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LoginRequest.passwd)
}
inline void LoginRequest::set_passwd(const char* value, size_t size) {
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LoginRequest.passwd)
}
inline ::std::string* LoginRequest::mutable_passwd() {
  
  // @@protoc_insertion_point(field_mutable:LoginRequest.passwd)
  return passwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_passwd() {
  // @@protoc_insertion_point(field_release:LoginRequest.passwd)
  
  return passwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_passwd(::std::string* passwd) {
  if (passwd != NULL) {
    
  } else {
    
  }
  passwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd);
  // @@protoc_insertion_point(field_set_allocated:LoginRequest.passwd)
}

inline const LoginRequest* LoginRequest::internal_default_instance() {
  return &LoginRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// LoginResponse

// optional int32 response_code = 1;
inline void LoginResponse::clear_response_code() {
  response_code_ = 0;
}
inline ::google::protobuf::int32 LoginResponse::response_code() const {
  // @@protoc_insertion_point(field_get:LoginResponse.response_code)
  return response_code_;
}
inline void LoginResponse::set_response_code(::google::protobuf::int32 value) {
  
  response_code_ = value;
  // @@protoc_insertion_point(field_set:LoginResponse.response_code)
}

inline const LoginResponse* LoginResponse::internal_default_instance() {
  return &LoginResponse_default_instance_.get();
}
// -------------------------------------------------------------------

// UserInfo

// optional int32 identify_id = 1;
inline void UserInfo::clear_identify_id() {
  identify_id_ = 0;
}
inline ::google::protobuf::int32 UserInfo::identify_id() const {
  // @@protoc_insertion_point(field_get:UserInfo.identify_id)
  return identify_id_;
}
inline void UserInfo::set_identify_id(::google::protobuf::int32 value) {
  
  identify_id_ = value;
  // @@protoc_insertion_point(field_set:UserInfo.identify_id)
}

// optional int32 channel_num = 2;
inline void UserInfo::clear_channel_num() {
  channel_num_ = 0;
}
inline ::google::protobuf::int32 UserInfo::channel_num() const {
  // @@protoc_insertion_point(field_get:UserInfo.channel_num)
  return channel_num_;
}
inline void UserInfo::set_channel_num(::google::protobuf::int32 value) {
  
  channel_num_ = value;
  // @@protoc_insertion_point(field_set:UserInfo.channel_num)
}

// optional int32 session_num = 3;
inline void UserInfo::clear_session_num() {
  session_num_ = 0;
}
inline ::google::protobuf::int32 UserInfo::session_num() const {
  // @@protoc_insertion_point(field_get:UserInfo.session_num)
  return session_num_;
}
inline void UserInfo::set_session_num(::google::protobuf::int32 value) {
  
  session_num_ = value;
  // @@protoc_insertion_point(field_set:UserInfo.session_num)
}

inline const UserInfo* UserInfo::internal_default_instance() {
  return &UserInfo_default_instance_.get();
}
// -------------------------------------------------------------------

// SyncInfo_S_User

// optional int32 user_id = 1;
inline void SyncInfo_S_User::clear_user_id() {
  user_id_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::user_id() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.user_id)
  return user_id_;
}
inline void SyncInfo_S_User::set_user_id(::google::protobuf::int32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.user_id)
}

// optional int32 x_pos = 2;
inline void SyncInfo_S_User::clear_x_pos() {
  x_pos_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::x_pos() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.x_pos)
  return x_pos_;
}
inline void SyncInfo_S_User::set_x_pos(::google::protobuf::int32 value) {
  
  x_pos_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.x_pos)
}

// optional int32 y_pos = 3;
inline void SyncInfo_S_User::clear_y_pos() {
  y_pos_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::y_pos() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.y_pos)
  return y_pos_;
}
inline void SyncInfo_S_User::set_y_pos(::google::protobuf::int32 value) {
  
  y_pos_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.y_pos)
}

// optional int32 vec = 4;
inline void SyncInfo_S_User::clear_vec() {
  vec_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::vec() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.vec)
  return vec_;
}
inline void SyncInfo_S_User::set_vec(::google::protobuf::int32 value) {
  
  vec_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.vec)
}

// optional int32 type = 5;
inline void SyncInfo_S_User::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::type() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.type)
  return type_;
}
inline void SyncInfo_S_User::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.type)
}

// optional int32 A_type_pow = 6;
inline void SyncInfo_S_User::clear_a_type_pow() {
  a_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::a_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.A_type_pow)
  return a_type_pow_;
}
inline void SyncInfo_S_User::set_a_type_pow(::google::protobuf::int32 value) {
  
  a_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.A_type_pow)
}

// optional int32 B_type_pow = 7;
inline void SyncInfo_S_User::clear_b_type_pow() {
  b_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::b_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.B_type_pow)
  return b_type_pow_;
}
inline void SyncInfo_S_User::set_b_type_pow(::google::protobuf::int32 value) {
  
  b_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.B_type_pow)
}

// optional int32 C_type_pow = 8;
inline void SyncInfo_S_User::clear_c_type_pow() {
  c_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_S_User::c_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.User.C_type_pow)
  return c_type_pow_;
}
inline void SyncInfo_S_User::set_c_type_pow(::google::protobuf::int32 value) {
  
  c_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_S.User.C_type_pow)
}

inline const SyncInfo_S_User* SyncInfo_S_User::internal_default_instance() {
  return &SyncInfo_S_User_default_instance_.get();
}
// -------------------------------------------------------------------

// SyncInfo_S

// repeated .SyncInfo_S.User users = 1;
inline int SyncInfo_S::users_size() const {
  return users_.size();
}
inline void SyncInfo_S::clear_users() {
  users_.Clear();
}
inline const ::SyncInfo_S_User& SyncInfo_S::users(int index) const {
  // @@protoc_insertion_point(field_get:SyncInfo_S.users)
  return users_.Get(index);
}
inline ::SyncInfo_S_User* SyncInfo_S::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:SyncInfo_S.users)
  return users_.Mutable(index);
}
inline ::SyncInfo_S_User* SyncInfo_S::add_users() {
  // @@protoc_insertion_point(field_add:SyncInfo_S.users)
  return users_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::SyncInfo_S_User >*
SyncInfo_S::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:SyncInfo_S.users)
  return &users_;
}
inline const ::google::protobuf::RepeatedPtrField< ::SyncInfo_S_User >&
SyncInfo_S::users() const {
  // @@protoc_insertion_point(field_list:SyncInfo_S.users)
  return users_;
}

inline const SyncInfo_S* SyncInfo_S::internal_default_instance() {
  return &SyncInfo_S_default_instance_.get();
}
// -------------------------------------------------------------------

// SyncInfo_C

// optional int32 user_id = 1;
inline void SyncInfo_C::clear_user_id() {
  user_id_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::user_id() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.user_id)
  return user_id_;
}
inline void SyncInfo_C::set_user_id(::google::protobuf::int32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.user_id)
}

// optional int32 x_pos = 2;
inline void SyncInfo_C::clear_x_pos() {
  x_pos_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::x_pos() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.x_pos)
  return x_pos_;
}
inline void SyncInfo_C::set_x_pos(::google::protobuf::int32 value) {
  
  x_pos_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.x_pos)
}

// optional int32 y_pos = 3;
inline void SyncInfo_C::clear_y_pos() {
  y_pos_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::y_pos() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.y_pos)
  return y_pos_;
}
inline void SyncInfo_C::set_y_pos(::google::protobuf::int32 value) {
  
  y_pos_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.y_pos)
}

// optional int32 vec = 4;
inline void SyncInfo_C::clear_vec() {
  vec_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::vec() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.vec)
  return vec_;
}
inline void SyncInfo_C::set_vec(::google::protobuf::int32 value) {
  
  vec_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.vec)
}

// optional int32 type = 5;
inline void SyncInfo_C::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::type() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.type)
  return type_;
}
inline void SyncInfo_C::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.type)
}

// optional int32 A_type_pow = 6;
inline void SyncInfo_C::clear_a_type_pow() {
  a_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::a_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.A_type_pow)
  return a_type_pow_;
}
inline void SyncInfo_C::set_a_type_pow(::google::protobuf::int32 value) {
  
  a_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.A_type_pow)
}

// optional int32 B_type_pow = 7;
inline void SyncInfo_C::clear_b_type_pow() {
  b_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::b_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.B_type_pow)
  return b_type_pow_;
}
inline void SyncInfo_C::set_b_type_pow(::google::protobuf::int32 value) {
  
  b_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.B_type_pow)
}

// optional int32 C_type_pow = 8;
inline void SyncInfo_C::clear_c_type_pow() {
  c_type_pow_ = 0;
}
inline ::google::protobuf::int32 SyncInfo_C::c_type_pow() const {
  // @@protoc_insertion_point(field_get:SyncInfo_C.C_type_pow)
  return c_type_pow_;
}
inline void SyncInfo_C::set_c_type_pow(::google::protobuf::int32 value) {
  
  c_type_pow_ = value;
  // @@protoc_insertion_point(field_set:SyncInfo_C.C_type_pow)
}

inline const SyncInfo_C* SyncInfo_C::internal_default_instance() {
  return &SyncInfo_C_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2eproto__INCLUDED
